name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install prerender browser
        run: npx playwright install --with-deps chromium

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          ./node_modules/.bin/gh-pages -d build --dotfiles
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          
  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify Telegram
        uses: up9cloud/action-notify@v0.4
        env:
          GITHUB_JOB_STATUS: ${{ needs.build.result }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TEMPLATE_PATH: .github/telegram-notification.txt
          NOTIFY_ACTOR: ${{ github.actor }}
          NOTIFY_BRANCH: ${{ github.ref_name }}
          NOTIFY_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          NOTIFY_COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
